# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "The Blog of Oleksandr Mostepaniuk"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "http://mostepaniuk.com"

twitter_username: amost
github_username:  omostepaniuk

# Build settings
markdown: kramdown

gems: ['jekyll-paginate', 'jekyll-multiple-languages']

languages: ['en', 'ru']

language_default: 'en'

# pagination settings

paginate: 5
paginate_path: "/blog/page:num/"
