# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "The Blog of Oleksandr Mostepaniuk"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of Oleksandr Mostepaniuk
baseurl: "/"
url: "http://mostepaniuk.com"

# Build settings
markdown: kramdown

gems: ['jekyll-paginate', 'jekyll-multiple-languages']

languages: ['en', 'ru']

language_default: 'en'

excerpt_separator: "<!--more-->"

# pagination settings

paginate: 5
paginate_path: "/blog/page:num/"

environment: "development"
